name: 'Pull Request'
on:
  pull_request:
    branches:
      - master

jobs:
  pull_request:
    runs-on: ubuntu-latest
    name: testing local tag check
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./.github/local_action/ # Uses an action in the root directory
        id: local_action
        with:
          github-token: ${{ secrets.github_token }}
          tags: "test, test1, test2"
          tag-map: "common_tags"
          paths-to-terraform-dirs: "terraform/deploy/app/, terraform/modules/"
